behaviors:
  Agent Controller:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 100000
      learning_rate: 0.0003
      beta: 0.03
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    threaded: true
    summary_freq: 50000
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 64
    summary_freq: 30000